name: Maven Build and Test

on:
  push:
    branches:
      - GA

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          java-package: 'jdk'
          architecture: 'x64'

      - name: Set up Maven Wrapper
        run: .\mvnw wrapper --distribution-type bin

      - name: Build with Maven
        env:
          DISTRIBUTION: wrapper
        run: |
          ./mvnw -Dmaven.repo.local=repo compile
          MAVEN_OPTS="-Dmaven.repo.local=repo" ./mvnw -Dmaven.repo.local=repo compile

      - name: Run Unit Tests
        env:
          MAVEN_OPTS: -Dmaven.repo.local=repo
        run: ./mvnw -Dmaven.repo.local=repo test
