name: Maven Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Java JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Build with Maven
        run: mvn -B -DskipITs=${{ env.SKIP_INTEGRATION_TESTS }} clean package

      - name: Run unit tests
        run: mvn -B test

      - name: Run integration tests
        if: env.SKIP_INTEGRATION_TESTS != 'true'
        run: mvn -B failsafe:integration-test
