name: Maven Build and Test
on:
  push:
    branches:
      - GA

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          java-package: 'jdk'
          architecture: 'x64'
          check-latest: false

      - name: Configure JDK distribution
        run: |
          echo "<settings><profiles><profile><id>jdk17</id><activation><activeByDefault>true</activeByDefault></activation><properties><java.home>\${env.JAVA_HOME}</java.home></properties></profile></profiles></settings>" > $HOME/.m2/settings.xml

      - name: Build with Maven
        run: .\mvnw compile

      - name: Run Unit Tests
        run: .\mvnw test
