name: Maven Build and Test

on:
  push:
    branches:
      - master
      - feature_3

  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          java-package: 'jdk'
          architecture: 'x64'

      - name: Build with Maven
        run: mvn -B -DskipTests=true compile

      - name: Run Unit Tests
        run: mvn -B test

      - name: Build with Maven and Run SonarCloud analysis
        run: mvn -B -DskipTests=true org.sonarsource.scanner.maven:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN