name: Maven Build and Test

on:
  push:
    branches:
      - GA

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          java-package: 'jdk'
          architecture: 'x64'

      - name: Set up Maven Wrapper
        run: mvn wrapper --distribution-type bin

      - name: Build with Maven
        run: mvn -B -DskipTests=true compile

      - name: Run Unit Tests
        run: mvn -B test