name: Maven Build and Test

on:
  push:
    branches:
      - GA

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          java-package: 'jdk'
          architecture: 'x64'

      - name: Set up Maven Wrapper
        run: |
          chmod +x ./mvnw
          ./mvnw wrapper --maven-version 3.8.3

      - name: Build with Maven Wrapper
        run: ./mvnw -DskipTests=true compile

      - name: Run Unit Tests
        run: ./mvnw test
