name: Maven Build and Test

on:
  push:
    branches:
      - GA

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          java-package: 'jdk'
          architecture: 'x64'

      - name: Set up Maven Wrapper
        run: .\mvnw wrapper --distribution-type bin

      - name: Build with Maven
        run: .\mvnw -Dmaven.repo.local=repo compile
        env:
          MAVEN_OPTS: -Dmaven.repo.local=repo
        with:
          distribution: wrapper

      - name: Run Unit Tests
        run: .\mvnw -Dmaven.repo.local=repo test
        env:
          MAVEN_OPTS: -Dmaven.repo.local=repo